import "./globals.css";
import Navbar from "@/components/Navbar";



export const metadata = {
  title: "Ikrams Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <Navbar></Navbar>
       <div>
       {children}
       </div>

       <footer>
        <h1>this is footer</h1>
       </footer>
      </body>
    </html>
  );
}
